name: GDrive

on:
  push:
    paths: links.json
  watch:
    types: [ started ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Get Share Link
      id: link
      run: echo "::set-output name=gds::$(jq -r .gdrive_link links.json)"
    - name: Download file
      run: |
        sudo apt install perl wget 
        git clone https://github.com/Insouciant21/gdown.pl.git gd/
        cd gd
        ./gdown.pl ${{ steps.link.outputs.gds }}
        cat logcat.txt | grep Content-Disposition: | cut -d "'" -f 3 > filename.txt
        sed -i '2,$d' filename.txt
    - name: Filename
      id: fn
      run: echo "::set-output name=fn::$(cat gd/filename.txt)"
    - name: Upload
      run: |
        cp -r gd/${{ steps.fn.outputs.fn }} .
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ${{ steps.fn.outputs.fn }} > tmp.txt
        cat tmp.txt | grep Download | cut -d ' ' -f 3 > gdlink.txt
    - name: Push File
      run: |
        git config --global user.email "48847364+Insouciant21@users.noreply.github.com"
        git config --global user.name "Insouciant21"
        git add gdlink.txt
        git commit -m "link"
        git push
        
        
        
